#! /bin/bash

BUILD_MODE=$1
PREFIX_MODE=$2
CPU_NUM=$3

function Usage() {
	echo "Usage: $0"
	echo
	echo "Configuration:"
	echo "-h, --help              Display this help and exit"
	echo
	echo "For better control, use the options below."
	echo
	echo "Optional features:"
	echo "-d, --debug             Enable debug mode"
	echo "-r, --release           Enable release mode"
	echo " 1, --prebuilts         Local build"
	echo " 2, --download          Board Target build"
	exit 1
}

PREFIX_MENU_CHOICES=(prebuilts download)

#
# File execute permission check
#
if [ ! -x configure ]; then
	chmod +x configure
fi

#
# Check for options
#
gst_opt_debug="--disable-debug"

invalid_args="false"
change_config=no
	case $BUILD_MODE in
	-r | --release)
		gst_opt_debug="--disable-debug"
		;;
	-d | --debug)
		gst_opt_debug=""
		;;
	-h | --help)
		Usage $@
		;;
	*)
		echo "\"$BUILD_MODE\" is invalid argument!"
		echo "Augument is either \"release\" or \"debug\"."
		invalid_args="true"
		;;
	esac

if [ $invalid_args = "true" ]; then
	echo "Please, recheck and try again."
	exit 1
fi

enable_wmv78dec=no
gst_opt_wmv78dec="--disable-wmv78dec"
if [ "${enable_wmv78dec}" = "yes" ]; then
gst_opt_wmv78dec="--enable-wmv78dec"
fi

#
# Directory settings
#
current_dir=`pwd`
#project_dir=`expr "${current_dir}" : '\(.*\)/gstreamer/.*'`
project_dir=$LINUX_PLATFORM_ROOTDIR
prebuilts_dir=/prebuilts
download_dir=/$BUILDDIR/videocodec
tcc_install_dir='/home/A990064/Gstreamer/ZEUS_TEST'
if [ "${tcc_install_dir:-unset}" = "unset" -o "${tcc_install_dir}" != "${project_dir}" ]; then
	change_config=yes
fi

if [ "${change_config}" = "yes" ]; then
	tcc_install_dir=`echo ${project_dir} | sed -e 's/\//\\\\\//g'`
	# tccvideocodec_build
	sed -e "s/^tcc_install_dir=.*/tcc_install_dir='${tcc_install_dir}'/" $0 > temp_build.$$
	chmod +x temp_build.$$
	# Execute tccvideocodec_build
	/bin/bash temp_build.$$ $@
	if [ $? -ne 0 ]; then
		rm -rf temp_build.$$
		exit $?
	fi
	mv -f temp_build.$$ $0
	exit
fi

#
# Check for prefix
#
if (echo -n $PREFIX_MODE | grep -q -e "^[0-9][0-9]*$")
then
	if [ $PREFIX_MODE -le ${#PREFIX_MENU_CHOICES[@]} ]
	then
		selection=${PREFIX_MENU_CHOICES[$(($PREFIX_MODE-1))]}
	fi
fi

if [ "$selection" = "" ]; then
	echo
	echo "Invalid prefix: $PREFIX_MODE"
	exit
elif [ "$selection" = "prebuilts" ]; then
	tcc_prefix_dir=${tcc_install_dir}${prebuilts_dir}
	echo " 1, --prebuilts         Local build"
elif [ "$selection" = "download" ]; then
	tcc_prefix_dir=${tcc_install_dir}${download_dir}
	echo " 2, --download          Board Target build"
fi

# reconfigure : do not remove below line
echo "run autoreconf"
autoreconf -ivf

#
# Configure
#

if [ "$LINUX_PLATFORM_MACHINE" = "tcc892x" ]; then
	chipname="tcc892x"
	#chipname="tcc8925s"
	target_cflag="-mcpu=arm1176jzf-s -mfloat-abi=softfp -mfpu=vfp -DTCC_892x_INCLUDE"
	host_name="arm-none-linux-gnueabi"
	target_name="arm-none-linux-gnueabi"
elif [ "$LINUX_PLATFORM_MACHINE" = "tcc8930" ]; then
	chipname="tcc893x"
	#chipname="tcc8935s"
	target_cflag="-mcpu=arm1176jzf-s -mfloat-abi=softfp -mfpu=vfp -DTCC_893x_INCLUDE"
	host_name="arm-none-linux-gnueabi"
	target_name="arm-none-linux-gnueabi"
elif [ "$LINUX_PLATFORM_MACHINE" = "tcc8960" ]; then
	chipname="tcc896x"
	target_cflag="-mcpu=cortex-a7 -mfloat-abi=softfp -mfpu=neon-vfpv4 -DTCC_896x_INCLUDE"
	host_name="arm-none-linux-gnueabi"
	target_name="arm-none-linux-gnueabi"
elif [ "$LINUX_PLATFORM_MACHINE" = "tcc8970" ]; then
	chipname="tcc897x"
	target_cflag="-mcpu=cortex-a7 -mfloat-abi=softfp -mfpu=neon-vfpv4 -DTCC_897x_INCLUDE"
	host_name="arm-none-linux-gnueabi"
	target_name="arm-none-linux-gnueabi"
elif [ "$LINUX_PLATFORM_MACHINE" = "tcc898x" ]; then
	chipname="tcc898x"
	target_cflag="-mcpu=cortex-a7 -mfloat-abi=softfp -mfpu=neon-vfpv4 -DTCC_898x_INCLUDE"
	#host_name="arm-unknown-linux-gnueabi"
	#target_name="arm-unknown-linux-gnueabi"
	host_name="arm-none-linux-gnueabi"
	target_name="arm-none-linux-gnueabi"
fi

./configure \
			--build=i686-pc-linux-gnu --host=${host_name} --target=${target_name} \
			${gst_opt_wmv78dec} \
			--prefix=${tcc_prefix_dir} \
			CPPFLAGS="-I${tcc_install_dir}${prebuilts_dir}/include" \
			CFLAGS="$target_cflag" \
			LDFLAGS="-L${tcc_install_dir}${prebuilts_dir}/lib" \
			PKG_CONFIG_PATH="${tcc_install_dir}${prebuilts_dir}/lib/pkgconfig" \
			PROCESSOR="$chipname"

#
# Clean
#
make clean

#
# Compile
#
make $CPU_NUM

#
# Install
#
make install

if [ "$selection" = "download" ]; then
	cp -rf $tcc_prefix_dir/* $tcc_install_dir/$BUILDDIR/tccgst/
fi
